### ISSUE TITLE
artifactCleanup cleaning all the other repos to

### ISSUE THREAD

**Issue by meedel** [JFrogDev/artifactory-user-plugins#121]
I had trouble with our automatic artifactCleanup process.
We have a Jenkins job to submit the cleaning through a curl command. 
It wasn't working anymore. I found out that the field seperator has changed!?  It was | and nou ; 
( but that was a change for 5.x !? )

I submitted a single repo clean from the command line:
curl -X POST -v -u admin:xxxxxx "http://ota-artifactory1.so.kadaster.nl:8090/artifactory/api/plugins/execute/cleanup?params=months=2;repos=mvn-snapshot-local;paceTimeMS=200"

In the artifactory logging I saw that many other repo's were allso cleaned ???
How is that possible.

I was happy to know artifactory has a trash can. So I could place the deleted artifacts from the other repo's back in place. 

We are running artifactory 4.16.1

The message I get back in the artifactory log is:

2017-08-09 18:29:21,522 [http-nio-8081-exec-6767] [INFO ] (artifactCleanup     :90) - Starting artifact cleanup for repositories null, until 6 months ago with pacing interval 0 ms dryrun: false

**Comment by elioengcomp** [comment]
@meedel the separator change only applies for Artifactory version 5.x. Since you are running 4.16.1, I should still use pipes to make the cleanup request.

**Comment by DarthFennec** [comment]
The field separator has always been `|`, but Artifactory 5.x runs on a newer version of Tomcat which doesn't support unencoded `|` characters, and will respond with a 400 error when it sees them. Because of this, Artifactory 5.0 introduced `;` as an alternative. More information can be found in the [release notes](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.0). If you are using Artifactory 4.x, you should continue to use the `|`.

There are a few reasons it might clean repositories other than the one you specified:

- If you are running Artifactory 4.x, it will not interpret the `;` characters as separators, so the values of your parameters will be `2;repos=mvn-snapshot-local;paceTimeMS=200` for `months`, and `null` for `repos` and `paceTimeMS`. When `repos` is `null`, the plugin cleans all repositories by default.
- If you have an `artifactCleanup.properties` file, it may contain definitions for periodic jobs to clean other repositories.

**Comment by meedel** [comment]
Thanks for your replies. So I can't use this feature anymore with artifactory 4.x! ( with curl )

I wil use the  artifactCleanup.properties  instead.  The explanation how to use this file is not present anymore?
 
I am upgrading to 5.x, but that's a difficult job to do in our environment.

**Comment by meedel** [comment]
Is this the correct way to implement a cleanrun every midnight?

// Support different policies for different repos. Parameters between '|' are optional
// Policy syntax: [ <cron time>, [ <repo list> ], months |, <pause time>, <true|false dryrun> | }
// Example: [ "0 0 5 ? * 1", [ "libs-releases-local" ], 3, 500, true ],
policies = [
               [ "0 0 * * * 1", [ "mvn-snapshot-local" ], 2 ],
               [ "0 0 * * * 1", [ "bower-snapshot-local" ], 2 ],
               [ "0 0 * * * 1", [ "npm-snapshot-local" ], 2 ],
               [ "0 0 * * * 1", [ "nuget-snapshot-local" ], 2 ],
           ]

**Comment by meedel** [comment]
We have version 4.6.1 of Artifactory. When I use the | separator with the curl command I get a 400  error.
I think at the last upgrade to 4.6.1 we got a newer verison of tomcat!?

**Comment by elioengcomp** [comment]
@meedel the cron expression you are using will trigger the job execution hourly every Sunday. If you want it to trigger the job daily at midnight we should use "0 0 0 * * ?"

**Comment by DarthFennec** [comment]
If you're using the Tomcat that Artifactory comes packaged with, and not copying the war file to a separate Tomcat instance or something, then you shouldn't be having that problem. I don't seem to have an issue when I try it in 4.6.1. Could you provide the curl command that you're using?

if the issue you're having is in fact the Tomcat issue, percent-encoding your pipe characters should fix it: instead of `|` or `;`, use `%7C`. This should work in all versions of Artifactory and Tomcat. if you still get 400 errors, something else is wrong.

**Comment by meedel** [comment]
@elioengcomp Thanks. 

@DarthFennec  Using the %7C was the right solution. It works fine for me now. 
We use the default docker instances provided by Jfrog. So I don't know what went wrong with the 4.6.1 version. I'm migrating to version 5.4.3 So for the time being I can use the %7C notation. Thanks

The curl command I used was: 
curl -X POST -v -u admin:xxxxxxxx "http://ota-artifactory1.so.kadaster.nl:8090/artifactory/api/plugins/execute/cleanup?params=months=2|repos=mvn-snapshot-local|paceTimeMS=200

But this one gives me a 400 Bad Request
