### ISSUE TITLE
Lack of documentation for security plugins

### ISSUE THREAD

**Issue by ometa** [JFrogDev/artifactory-user-plugins#66]
Hello!

I am new to the JFrog community and am checking out the security plugins.  I noticed a lack of documentation, and some inconsistencies, which I am documenting here.
### Documentation is the same, and vague
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/delegateAuthenticationRealm
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/getCurrentUserDetails

No Documentation for these:
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/protectPropertiesEdit
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/synchronizeLdapGroups
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/synchronizeUserKeys

An example of decent documentation:
- https://github.com/JFrogDev/artifactory-user-plugins/tree/master/security/preventOverride

**Comment by DarthFennec** [comment]
Hi, welcome!

We are aware that many of the plugins in this repository lack proper documentation and testing. I've been working to rectify this (the vast majority of the documentation and tests that do exist were written by me), but I don't often have much time to spare for it, so it's a slow process. If you would like to help speed things up, you are free to submit a pull request. Otherwise, I'll get to it whenever I have time.

**Comment by ometa** [comment]
Hi @DarthFennec and thanks for the reply!  I am happy to submit a PR for documentation if I end up using any of these plugins.  I have a feeling I'll be using the delegateAuthenticationRealm and getCurrentUserDetails, soon.

Cheers!

**Comment by DarthFennec** [comment]
Thanks for the input, it's always appreciated. I took some time today to update the README files for the delegateAuthenticationRealm and getCurrentUserDetails plugins. I hope this new documentation proves more useful. Let me know what you think.
