### ISSUE TITLE
securityReplication does not work with LDAP users

### ISSUE THREAD

**Issue by melkamar** [JFrogDev/artifactory-user-plugins#79]
I am in process of merging two used-to-be-separate Artifactory instances (4.x) and the securityReplication plugin does not correctly sync encrypted passwords or API keys of LDAP users.

Local users work without an issue, for LDAP users I can see in the log that a patch is created and sent, but nothing changes in the slave instance.

**Comment by DarthFennec** [comment]
We've recently discovered an issue with that plugin, which causes it to behave incorrectly when installed on instances in different initial states. We're currently working to fix this.

Although, it does strike me as particularly odd that local users would sync, but LDAP users wouldn't ... the plugin doesn't distinguish between the two, after all, and Artifactory doesn't either, in any meaningful way.

To be sure of whether or not this issue is related to the one we're already working on, I'd like to clarify some things:

- Does the plugin work properly for *LDAP* users that were created *before* the plugin was installed?
- Does the plugin work properly for *local* users that were created *before* the plugin was installed?
- Does the plugin work properly for *LDAP* users that were created *after* the plugin was installed?
- Does the plugin work properly for *local* users that were created *after* the plugin was installed?
- Do the logs on the slave instance have anything strange in them, possibly related to this issue?

Thanks for bringing this up!

**Comment by edpeixoto1** [comment]
Good job communicating that.

**Comment by melkamar** [comment]
Oddly enough, I am not able to reproduce the issue on a restored snapshot of my testing VM. The VM where the issue was present is gone, sadly. All four scenarios are working for me at this point (as far as I can tell) with one caveat. This following paragraph may be the case that had happened to me before.

In order to set up the replication properly, I had to call the `api/plugins/execute/distSecRep` endpoint twice. If I did not do that, the replication would not happen. See the following gist and explanation below: [securityReplication error gist](https://gist.github.com/melkamar/4ec934cc58353ebc30b3e48cef115437)

Gist contents:

- `ERROR - initialize sync script`
  This is an initialization script that copies `securityReplication.{json,groovy}` files into the appropriate folder in the MASTER Artifactory instance (`root_artf1`). The replication is not done correctly after this script is run (removing the sleeping does not affect anything). The `artifactory.log` of both MASTER and SLAVE in this scenario are called `XXXXX artifactory.log - single call` and they contain everything from the initialization through several iterations of the replication.

- `OK - initialize sync script`
  This init script executes the `$ curl -uadmin:password -XPOST http://localhost:8081/artifactory/api/plugins/execute/distSecRep` twice. As a result, the replication starts working normally. Log files for this scenario are named `XXXXX artifactory.log - after second call`

- `securityReplication.json` is unsurprisingly the plugin configuration used by the MASTER instance on plugin initialization. The URLs are valid, Artifactories run in Docker via docker-compose and they can reach each other.

- `docker-compose.yml` - for completeness' sake, that is the "setup" I have been using to test all the scenarios.

----------------------------

Not sure if this belongs here, but - is it "safe" to decrypt passwords of two running and actively-used Artifactory instances? Will this affect the current API keys and encrypted passwords of users? I have found that the plugin only works when both sides are unencrypted. - Put briefly, will users still be able to use the same API key/password when I decrypt and re-encrypt the storage?

**Comment by DarthFennec** [comment]
Yes, this does sound like it's the same issue we've experienced. The fact that you have to call `distSecRep` a second time is telling:

The plugin currently has a 'disaster recovery mode' that causes it to run a full data merge if it detects that Artifactory has had down time. It detects this by reading the `startTime` field in the `securityReplication.json` file, and comparing it to Artifactory's actual start time. However, when `distSecRep` runs the second time, it overwrites the `securityReplication.json` file (including this field) with that of another instance. This causes the timestamp to be wrong, which triggers disaster recovery and a full merge. From the logs you posted:

```
2017-03-03 12:34:00,082 [http-nio-8081-exec-3] [DEBUG] (securityReplication :416) - ALL: artStartTime: 1488449584957
2017-03-03 12:34:00,082 [http-nio-8081-exec-3] [DEBUG] (securityReplication :417) - All: plugin startTime: 1488449584957
2017-03-03 12:34:00,083 [http-nio-8081-exec-3] [DEBUG] (securityReplication :434) - ALL: steady state nothing to do
####################
### called $ curl -uadmin:password -XPOST http://localhost:8081/artifactory/api/plugins/execute/distSecRep
####################
2017-03-03 12:35:00,064 [art-exec-2] [DEBUG] (securityReplication :-1) - ALL: artStartTime: 1488449584957
2017-03-03 12:35:00,066 [art-exec-2] [DEBUG] (securityReplication :-1) - All: plugin startTime: 1488449572139
2017-03-03 12:35:00,070 [art-exec-2] [DEBUG] (securityReplication :427) - ALL: plugin is in disaster recovery mode
```

When we complete this next update, that field won't exist anymore, and the plugin will no longer depend on timestamps. The plugin should be much more robust all around, and these kinds of synchronization issues should just vanish for the most part.

When you ask about encrypting and decrypting passwords, do you mean the the [Master Key Encryption](https://www.jfrog.com/confluence/display/RTF/Master+Key+Encryption) feature? The plugin should work correctly with this enabled, so if it isn't working for you, that's another problem we need to resolve. To answer your question though, master key encryption only affects how passwords are stored in the database, so it won't have any effect on how people use their passwords, encrypted passwords, or API keys.

**Comment by melkamar** [comment]
Thanks for the explanation. Do you have an ETA for the update? (next few weeks, months, later?) 

Would you consider this behavior 'safe enough' to apply to production environment?


And as for the last question, yes, I meant that feature. I guess I can just decrypt unencrypted Artifactory

**Comment by DarthFennec** [comment]
You should be able to turn master encryption on and off on a running production instance as much as you want with no noticeable or adverse effects, so yes, it's safe. The only unsafe thing I can think of is that leaving it off is slightly less secure (which is the reason it exists in the first place), as in if someone gets a dump of your database, they can see all your API keys and SSO secrets in plaintext (whereas if master encryption is on, they'll also need the master key, which means they'd also need access to the filesystem).

From the logs you posted, I now know what's causing the problem: there's been a small change to the internal API that the plugin uses to support master encryption, so whenever it tries to call that API, a MissingMethodException is thrown. The fix for this will be included in the next update, so after that you shouldn't have any more problems with master encryption.

As for the ETA, I need some time to finish the code, and then we need to run it through the test suite, but this is a top priority for us right now so it shouldn't take too long. Assuming everything goes well, I'd expect it sometime next week. Maybe the week after if there are unexpected issues. I'll keep you posted.

**Comment by DarthFennec** [comment]
@melkamar I'd like to let you know that we just pushed the update. It's stood up to everything we've thrown at it so far, but if you have any issues with the new version, don't hesitate to let us know. Thanks!
