### ISSUE TITLE
Fatal error loading artifactCleanup plugin

### ISSUE THREAD

**Issue by asarkar** [JFrogDev/artifactory-user-plugins#87]
Artifactory Pro v5.3.0

```
2017-05-14 02:10:28,393 [Thread-5] [INFO ] (o.a.c.c.ConfigurationManagerImpl:352) - [Node ID: e82128d978aa01c3:-ae144a7:15c04b4f4d7:-8000] detected local modify for config 'artifactory.plugin.artifactCleanup.groovy'
2017-05-14 02:10:28,418 [Thread-5] [INFO ] (o.a.c.c.ConfigurationManagerImpl:352) - [Node ID: e82128d978aa01c3:-ae144a7:15c04b4f4d7:-8000] detected local modify for config 'artifactory.plugin.artifactCleanup.properties'
2017-05-14 02:10:28,434 [http-nio-8081-exec-10] [INFO ] (o.a.a.p.PluginsAddonDefaultImpl:110) - Reloading plugins
2017-05-14 02:10:28,436 [http-nio-8081-exec-10] [INFO ] (o.a.a.p.GroovyRunnerImpl:244) - Loading script from 'artifactCleanup.groovy'.
2017-05-14 02:10:28,596 [http-nio-8081-exec-10] [ERROR] (o.a.a.p.GroovyRunnerImpl:300) - Error loading script from '/opt/jfrog/artifactory/etc/plugins/artifactCleanup.groovy'.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/opt/jfrog/artifactory/etc/plugins/artifactCleanup.groovy: 19: unable to resolve class Field ,  unable to find class for annotation
 @ line 19, column 1.
   @Field final String PROPERTIES_FILE_PATH = "plugins/${this.class.name}.properties"
   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310) ~[groovy-all-2.4.5.jar:2.4.5]
```

**Comment by asarkar** [comment]
Submitted PR https://github.com/JFrogDev/artifactory-user-plugins/pull/88

**Comment by DarthFennec** [comment]
Hello asarkar,

Thank you for pointing this out. There appear to actually be a handful of plugins that have this problem, so to simplify matters, I've just pushed a commit that fixes all of them.

**Comment by asarkar** [comment]
@DarthFennec Thank you. What's the commit SHA? And how did you verify that your change works, since it's now clear to me that these plugins are not actually verified by deploying with artifactory, because in that case, this fatal error would've surfaced long ago.

**Comment by DarthFennec** [comment]
The commit is a0f27970532f4e5b61daa1775d43092b1e182fe7. I verified the change by loading all the plugins into a local Artifactory instance and ensuring that there are no load errors, and also running the plugins' test files to ensure that those pass.

This error was introduced to all affected files by pull request #86, a couple weeks ago now it looks like. I was certain I tested that PR before accepting it, but it appears that I must have mistakenly not done so. I apologize, and I assure you that this is extremely abnormal. We don't allow untested code into this repository, and whenever a change is made to a plugin, it is verified by loading the plugin into Artifactory and running the automated test files.

This repo had a very ad-hoc beginning, and the introduction of any sort of testing into it was relatively recent (to the point where half of the plugins don't even have automated tests yet), so testing has historically been done manually, as our focus has primarily been about increasing coverage. More recently, we've started to build an internal test server for these plugins, which should be quite helpful in the future (in part by helping to prevent oversights like this one). In general, we work hard to continue to make this repository more stable and more useful.

**Comment by asarkar** [comment]
Thanks for the detail explanation. I submitted a PR too, with this fix as well some doc update. What do you suggest we do with it?

**Comment by bladster** [comment]
Hi can I ask what tools your using for testing?

**Comment by DarthFennec** [comment]
@bladster We developed this tool to help with plugin development and testing: https://github.com/JFrogDev/artifactory-user-plugins-devenv

@asarkar I can merge your doc changes if you'd like, but I have a few questions about them first:

- You changed "can be run" to "can be ran". The tense for this is future passive, which requires the past participle of "run", which is "run". So the original wording is the correct one.
- "Job schedule is read from a similarly named property file." I don't think this sentence is very clear. I'd maybe change it to something like "The job schedule can be specified in the `artifactCleanup.properties` file".
- I understand unindenting the logger snippet, but I could also understand leaving it as-is. The snippet will be indented in the `logback.xml` file, since it's supposed to go inside the `configuration` element. This is clear from the file itself, since there are many similar snippets already there, but if someone just copy/pastes this snippet into the file and the indentation is already correct, that just makes more sense to me. But I also see how it looks a little weird in the README itself. I'm willing to go either way on this.
- I'm not sure changing the examples to use `-G --url-encode` is the best option. It's less clear what the request actually looks like, especially if you're not all that well-versed in curl. I would personally prefer embedding the params into the URL, since that's what people are used to. On the other hand, it does need to be encoded, because recent versions of Tomcat will disallow the raw pipe characters. At the very least, those will need to be replaced with `%7C`, which may also be unclear ... so I'm not sure.

The rest of the changes look great.

**Comment by asarkar** [comment]
>  past participle of "run", which is "run"
ok.

> "Job schedule is read from a similarly named property file." I don't think this sentence is very clear. I'd maybe change it to something like "The job schedule can be specified in the artifactCleanup.properties file".

I somewhat agree, but then I kept it deliberately non-specific so that renaming doesn't become an issue. How many times have we all come across docs that don't match the code?

> logback.xml

Don't care about indenting, will do as suggested.

> 'm not sure changing the examples to use -G --url-encode is the best option....especially if you're not all that well-versed in curl

The `curl` samples, as given, doesn't work (on a Mac) as copy-pasted. The special chars have to be encoded, and when you're providing a curl sample, user not being well-versed in curl shouldn't be an excuse for wrong commands. The one I showed works by simply copy-paste, and for those that don't understand what `-G` or `--url-encode` do, my recommendation would be to RTFM.

**Comment by DarthFennec** [comment]
> I somewhat agree, but then I kept it deliberately non-specific so that renaming doesn't become an issue. How many times have we all come across docs that don't match the code?

True, but I really don't see name changes to be that big of an issue, as far as I know up to this point it's only ever happened one time. I just think the wording is a little confusing. Also, the name is used multiple times throughout the document, so I don't see how being vague in this one instance fixes that potential problem.

>The special chars have to be encoded, and when you're providing a curl sample, user not being well-versed in curl shouldn't be an excuse for wrong commands.

Yes, I agree that the pipes need to be escaped, and the commands need to be changed so that they're correct. I'm just suggesting replacing the pipes with `%7C` as an alternative. Using semicolons would also work, but only in Artifactory 5.x, so that may not be the best solution. The point is that these aren't commands that need to be run, they're just example HTTP requests. We could use any format to represent them, I just prefer curl because it's generally easy to tell what everything is from context alone, and it also happens to be easily copy-pasteable. But not every user is going to be using curl, or is even going to know curl, and I just think including (in my experience) a rather rarely used option that changes the behavior of a much more common option might be confusing to those people. Even if you don't know what `--data-urlencode` does, you could easily guess that it sets the request body, and you'd be right ... except in this case you wouldn't be, because of the `-G`.

I'm probably just overthinking it. There's nothing actually wrong with either of these, I just wanted to point out what I saw in case it ended up being constructive. You can keep both of these as-is if you'd like.

**Comment by asarkar** [comment]
Closed PR. There are dozens of other plugins in this repo showing the same format of `curl` that doesn't work. It isn't worth the time talking over for days.
